"""Tier 1 E2E Tests: Frontend Static Distribution Bundle.

Validates:
- frontend/dist/index.html exists and is non-empty
- index.html contains essential root element (<div id="root">) and HTML5 doctype
- Bundled assets (JS and CSS) referenced in index.html physically exist on disk
- Root HTTP endpoint (GET /) serves the compiled SPA index.html
"""

import re
from pathlib import Path
import pytest
import httpx

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DIST_DIR = PROJECT_ROOT / "frontend" / "dist"
INDEX_HTML = DIST_DIR / "index.html"


class TestFrontendStaticAssets:
    """Tier 1: Frontend production build artifacts verification."""

    def test_frontend_dist_index_html_exists(self):
        """Verify frontend/dist/index.html was generated by build."""
        assert INDEX_HTML.is_file(), (
            f"Production build missing: {INDEX_HTML} not found. "
            "Ensure 'npm run build' has completed successfully."
        )
        assert INDEX_HTML.stat().st_size > 0, f"index.html is empty at {INDEX_HTML}"

    def test_frontend_index_html_structure(self):
        """Verify index.html contains required DOM roots and module script tags."""
        if not INDEX_HTML.is_file():
            pytest.skip(f"Build artifact {INDEX_HTML} not generated yet.")

        content = INDEX_HTML.read_text(encoding="utf-8")
        
        # Check DOCTYPE
        assert "<!doctype html" in content.lower(), "index.html must declare HTML5 <!DOCTYPE html>"

        # Check React root mount point
        assert 'id="root"' in content, "index.html must contain React mount container <div id=\"root\">"

        # Check title tag
        assert "<title>" in content.lower(), "index.html must contain a <title> tag"

        # Check script module tag
        assert '<script type="module"' in content, "index.html must include Vite module entry <script type=\"module\" ...>"

    def test_frontend_bundled_assets_exist(self):
        """Verify referenced JS and CSS assets exist on disk in dist/assets/."""
        if not INDEX_HTML.is_file():
            pytest.skip(f"Build artifact {INDEX_HTML} not generated yet.")

        content = INDEX_HTML.read_text(encoding="utf-8")

        # Find script and stylesheet references
        script_matches = re.findall(r'<script[^>]+src=["\']([^"\']+)["\']', content)
        css_matches = re.findall(r'<link[^>]+href=["\']([^"\']+\.css)["\']', content)

        assert script_matches or css_matches, "index.html must reference at least one bundled JS/CSS asset"

        # Check referenced script files
        for script_src in script_matches:
            # Strip leading slash if present
            rel_path = script_src.lstrip("/")
            asset_path = DIST_DIR / rel_path
            assert asset_path.is_file(), f"Referenced JS asset not found on disk: {asset_path}"
            assert asset_path.stat().st_size > 100, f"Referenced JS asset is suspiciously small: {asset_path}"

        # Check referenced CSS files
        for css_href in css_matches:
            rel_path = css_href.lstrip("/")
            asset_path = DIST_DIR / rel_path
            assert asset_path.is_file(), f"Referenced CSS asset not found on disk: {asset_path}"
            assert asset_path.stat().st_size > 50, f"Referenced CSS asset is suspiciously small: {asset_path}"

    def test_frontend_served_at_root(self, api_client: httpx.Client):
        """Verify FastAPI serves index.html at GET /."""
        if not INDEX_HTML.is_file():
            pytest.skip(f"Build artifact {INDEX_HTML} not generated yet.")

        response = api_client.get("/")
        assert response.status_code == 200, f"Expected 200 for GET /, got {response.status_code}"
        assert 'id="root"' in response.text, "GET / response did not return React root element"
